services:
  dokploy:
    image: dokploy/dokploy:latest
    container_name: dokploy
    ports:
      - "3000:3000"
    environment:
      ADVERTISE_ADDR: ${ADVERTISE_ADDR}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dokploy_data:/etc/dokploy
      - dokploy_docker_config:/root/.docker
    depends_on:
      - postgres
      - redis
    networks:
      - dokploy-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: dokploy-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dokploy_postgres_database:/var/lib/postgresql/data
    networks:
      - dokploy-network
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: dokploy-redis
    volumes:
      - redis_data_volume:/data
    networks:
      - dokploy-network
    restart: unless-stopped

  traefik:
    image: traefik:v3.5.0
    container_name: dokploy-traefik
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dokploy-network
    restart: always

volumes:
  dokploy_data:
  dokploy_docker_config:
  dokploy_postgres_database:
  redis_data_volume:

networks:
  dokploy-network:
    driver: bridge
