services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 8095:8080
    volumes:
      - ~/Documents:/data
      - ~/homelab/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
